// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:950705e0-dd3e-4bf4-a5a1-027840fd15b0',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_VBjrV1sdN',
  aws_user_pools_web_client_id: '395b560l8go85v313svh5qrdqt',
  oauth: {},
};


export default awsmobile;